### ISSUE TITLE
Require Ruby >= 2.2

### ISSUE THREAD

**Issue by jimmycuadra** [litaio/lita#101]
Ruby keeps moving forward and Lita should too. 1.9 has already reached EOL and 2.0 will be next. 2.1 also has a few niceties like keyword arguments without default values.

**Comment by brodock** [comment]
:+1: do you have anything special in mind that will use 2.2. features, or just reducing maintenance burden?

**Comment by jimmycuadra** [comment]
Symbol GC would be nice, but feature-wise the main thing I want is keyword arguments without default values from Ruby 2.1. If I'm gonna be bumping the requirement, might as well make it 2.2.
