### ISSUE TITLE
Logging behaves unexpectedly

### ISSUE THREAD

**Issue by jnalley** [litaio/lita#106]
I ran into an issue that puzzled me for a bit until I figured out what was going on.  I'm not sure this is a bug, but thought I would mention the behavior I observe.

1. Generate a handler: ```$ lita handler foo```
2. Add ```Lita.logger.debug("hello")``` to ```lita-foo/lib/lita-foo.rb```
3. Set ```config.robot.log_level``` to ```:debug``` in lita_config.rb
4. Run ```lita``` and notice that the log message is not printed.

The problem is that using Lita.logger before the lita_config.rb has been read initializes the @logger singleton in lita.rb using the default log level (:info).  If logging is limited to the handler callbacks, everything works as expected.

**Comment by jimmycuadra** [comment]
That behavior makes sense given the load order of files/objects and the nature of Lita.logger as a singleton, though I agree it's not very obvious that it works like that. Maybe the first time the logger is accessed it should write to the log saying that what file/line called it and what its level was set to, to help trace down code that might be initializing it too early. Any other changes you think might help?

**Comment by jnalley** [comment]
What do you think about setting the level on each call to logger()?  This would solve the issue of the level "sticking" to the default level if called early.

```ruby
@logger.level = Logger.get_level_constant(config.robot.log_level)
```

**Comment by jimmycuadra** [comment]
I'm not sure that would really improve things, it'd continue to be an ordering issue except that the last one would win instead of the first one.

**Comment by jimmycuadra** [comment]
I think there isn't anything actionable for the time being, but please reopen if there is a way to improve here.
