### ISSUE TITLE
Configurable default handlers

### ISSUE THREAD

**Issue by assimovt** [litaio/lita#115]
Looks like Lita comes with default handlers, such as ```room```, ```info```, ```authorization```, etc. Is it possible to disable them via configuration flags? If not, do you think it would be a useful enhancement?

**Comment by natesholland** [comment]
I could see this being a useful feature. Especially if someone wanted to rewrite an implementation specific to their environment.

**Comment by assimovt** [comment]
What would happen currently if one adds, say ```info``` handler? Would it override?

**Comment by natesholland** [comment]
I did something similar where I monkey patched the rooms handler to allow non admins to invite lita to their room. There is more info about it in this PR: https://github.com/jimmycuadra/lita/pull/114

Basically you can probably override it and if you have any issues you can monkey patch the methods as described in that PR.

**Comment by assimovt** [comment]
Tbh, I'd prefer to disable some of the default handlers via configuration flags, and add my own. @jimmycuadra whats your opinion on this?

**Comment by jimmycuadra** [comment]
You can do it now by modifying `Lita.handlers` inside lita_config.rb. For example:

``` ruby
Lita.handlers.delete(Lita::Handlers::Info)
```

It's certainly possible to add configuration to disable them, but I'd be interested in hearing more about why you want to remove them before changing any code.

**Comment by assimovt** [comment]
If its that easy to configure through lita_config.rb, it should work for me. I have two use cases, first I will be providing custom help page via handler, and secondly I don't want the extra ones, for example users search. Thanks!
