### ISSUE TITLE
Mattermost Adapter

### ISSUE THREAD

**Issue by maxmeyer** [litaio/lita#152]
Hi, Gitlab seems to integrate mattermost into their omnibus packages. [Mattermost](http://mattermost.org) is an on-site alternative to slack. Is anybody working on an adapter? Their webhooks seem to be API compatible with (https://github.com/mattermost/platform/blob/master/doc/developer/API.md)[https://github.com/mattermost/platform/blob/master/doc/developer/API.md]. Is this enough for the slack adapter to work with mattermost?

**Comment by jimmycuadra** [comment]
I'm not aware of an existing Mattermost adapter, but if you use Mattermost, I'm sure the community would be quite appreciative if you create one! It's possible that lita-slack works with it if Mattermost attempts to keep their API compatible, but that is not a use case lita-slack will ever officially support.
