### ISSUE TITLE
Document Issue [Minor]

### ISSUE THREAD

**Issue by sjernigan** [litaio/lita#153]
On http://docs.lita.io/getting-started/installation/, I believe step 8 and `lita new .` should be swapped.  There is no Gemfile until you create the project.

**Comment by jimmycuadra** [comment]
Thanks for the report! The documentation website is open source, so I encourage you to fix it and open a pull request! :) https://github.com/litaio/docs.lita.io

**Comment by sjernigan** [comment]
Done.  Thanks - https://github.com/litaio/docs.lita.io/pull/12
