### ISSUE TITLE
How to use error_handler to send message?

### ISSUE THREAD

**Issue by ianneub** [litaio/lita#163]
Hello,

Is it possible to use the config `error_handler` proc to send a message back to the user over chat that an error occurred?

The `response` object isn't available of course, so I'm not quite sure how to access the robot or the chatroom.

Thanks!

**Comment by jimmycuadra** [comment]
It depends on what the error is. If it's a custom exception that your own plugin is raising, then you can store any data you like in the error object and access it from the error handler. For other error objects that you don't control, there isn't a good mechanism for this right now.

**Comment by ianneub** [comment]
Ah, good idea, thanks!
