### ISSUE TITLE
Handler reload in development mode

### ISSUE THREAD

**Issue by kirs** [litaio/lita#177]
Right now, if you change code of any handler, you have to restart the Lita process.
Sometimes we need to debug the handler in development mode when Lita is launched with shell adapter.
Maybe in development we could provide handler reloading after the class was changed?

@jimmycuadra

**Comment by kirs** [comment]
I'll be happy to work on this feature.

**Comment by jimmycuadra** [comment]
I'd rather not go down that road, really. Magic code reloading causes all sorts of subtle problems in Rails. Would it be possible to use some sort of file system watcher or process manager external to Lita to achieve what you want? Years ago I used the guard gem, but I'm not sure if that's still an active project or if it fits for this use case.

**Comment by kirs** [comment]
I think it would be possible for a process like RSpec or web server, not sure about CLI processes like the shell adaptor.

**Comment by jimmycuadra** [comment]
I think this is not something I want to add to the core gem. I do want anything a developer might want to be possible as an extension, though. If you want to try building this that way, please open issues for anything you're unable to achieve with the current extension system.

**Comment by itay-grudev** [comment]
Can this be reopened in 2021? Auto-reloading is something normal and quite stable nowadays - including in Rails.
