### ISSUE TITLE
Possibility to remove redis

### ISSUE THREAD

**Issue by eligiblekeng** [litaio/lita#179]
Is it possible to use `lita` without `redis`? In the case of a techop-restricted VM environment.

Or, if someone wishes to use a different db can one replace `redis` with something else?

**Comment by jimmycuadra** [comment]
No, for better or for worse, Lita has a hard dependency on Redis. This was an intentional design decision when I started it. It would be very difficult to make optional at this point because direct, programmatic access to Redis is part of Lita's plugin API.
