### ISSUE TITLE
Incompatible character encodings raised from Redis command helper

### ISSUE THREAD

**Issue by desktophero** [litaio/lita#180]
I opened a Gist to not spam this issue.

https://gist.github.com/desktophero/3d4a2c1f2d97989811d16308567e179a

I haven't nailed down specific scenarios or causes and the only response I am taking is to nuke the Redis data and restart Lita. I searched in other Issues and didn't find errors around encoding error messages. 

I'll add more details, like version, OS, etc., in a bit. I wanted to get this started and share the log from the Gist.

**Comment by jimmycuadra** [comment]
Not sure if it's the same root cause, but you might find some useful info in https://github.com/litaio/lita-hipchat/issues/3 or one of the issues referenced in it.

**Comment by desktophero** [comment]
My assumption is that it's in the data itself within Redis based on a user in HioChat.

I'll dig into the steps called out in the link. Thanks for that!

I'll report back tomorrow.

**Comment by desktophero** [comment]
After completing a few steps, it looks like for ~8 hours, no error message. 

- [ ] Stopped the Lita service
- [ ] Blew away `/opt/lita`
- [ ] Update `/etc/default/locale` (for Ubuntu) to include:
```
LANG=en_US.utf8
LC_ALL=en_US.utf8
```

Note: `LC_ALL` was not in place. Cloud-init controls the building of that script (for my use case; need to make sure that's baked)

- [ ] `flushall` in redis-cli (again, I'm not persisting long-term data; the cache is refreshed)
- [ ] Ran `chef-client` to rebuild all the things
- [ ] Validated Ruby default for encoding is UTF8
```
[2] pry(main)> Encoding.default_external
=> #<Encoding:UTF-8>
```
That last step, I /should/ have run prior to see if what's what. I'll be redeploying on a fresh VM soon so I can verify, if needed. Closing the issue.

Thanks again for the link!

**Comment by desktophero** [comment]
Did a little more digging and updated my Gist: https://gist.github.com/desktophero/3d4a2c1f2d97989811d16308567e179a

The `en dash` was used to create some room names. There's no value for that from UTF-8 to US-ASCII. I haven't looked at using the extended ASCII as part of Lita.
