### ISSUE TITLE
Provide a reply for unauthorized commands

### ISSUE THREAD

**Issue by crunis** [litaio/lita#181]
Currently, when using [authorization groups](https://docs.lita.io/getting-started/usage/#authorization-groups), commands are silently ignored if the user is not in the corresponding authorized groups. 

It would be useful to provide the ability to reply back to the user telling that the command can't be executed since he's not authorized, otherwise is not always clear if that's the case of there's a problem with the regex, or the bot is misbehaving, etc ...

Suggestions for this could be:
 * Configuraiton option with a string to display in these situations
 * Authorization hook to be called when this situation happens, providing the command executed, the user who did it, etc..

**Comment by jimmycuadra** [comment]
This is possible with the `:route_authorization_failed` event: https://docs.lita.io/plugin-authoring/events/

More discussion in #59.
