### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by eligiblekeng** [litaio/lita#182]
Can we allow lita to take an optional flag for production mode, just like in Rails: `lita -e production`? This shall set the `RAILS_ENV=production`; otherwise by default `RAILS_ENV=development`.

This is especially helpful when used with a `secrets.yml` file too. Right now it has to be read and the mode be chosen manually in `lita-config.rb`.

**Comment by jimmycuadra** [comment]
What would it do?

**Comment by jimmycuadra** [comment]
I don't think Lita should be doing anything with RAILS_ENV, as it has nothing do with Rails. Sounds like something that should exist in a plugin if it'd be useful for some custom setup. You might be interested in [lita-ext](https://github.com/railsmachine/lita-ext), which does something a little like what you're describing.

**Comment by eligiblekeng** [comment]
oh ok, I'll look into that. Thanks!
