### ISSUE TITLE
How to use lita?

### ISSUE THREAD

**Issue by NhaTrang** [litaio/lita#183]
Hi,
Can I use lita and teach him the answer to questions?
For example, I will fill out a database on how works wifi protocol and the chatbot will be able to give the answer on questions asked on wifi protocol communication.

Thanks

**Comment by jimmycuadra** [comment]
Lita is a framework for writing a chat bot in Ruby. It only provides an API for connecting to a chat service, sending and receiving messages, storing and retrieving data, etc. It's up to you to decide how to use it. You can install some of the [publicly available plugins](https://plugins.lita.io/) or [write your own](https://docs.lita.io/plugin-authoring/) to do anything you want. If you want to ask more questions, come visit our IRC channel: #lita.io on the Freenode network.
