### ISSUE TITLE
Lita vagrant development environment misses git

### ISSUE THREAD

**Issue by gbin** [litaio/lita#189]
If I follow the documentation between https://docs.lita.io/getting-started/installation/#development-environment and https://docs.lita.io/plugin-authoring/handlers/

The result is:
```
lita@4ac79d5e8890:~/workspace/lita$ lita handler hello
/home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:153:in ``': No such file or directory - git (Errno::ENOENT)
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:153:in `generate_user_config'
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:149:in `generate_config'
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:103:in `handler'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/lita/.gems/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
        from /home/lita/.gems/bin/lita:22:in `load'
        from /home/lita/.gems/bin/lita:22:in `<main>'
```

2 fixes need to be done:
- check if the git command is there before trying to invoke it and give a user friendly error
- add git in the lita docker image so it doesn't happen

The workaround of course:
```
lita@4ac79d5e8890:~/workspace/lita$ sudo apt-get install git
```

**Comment by jimmycuadra** [comment]
Thanks for the report. Once Docker for Mac/Windows comes out of beta I'm gonna revamp the development environment to be much simpler, and will take care of this then. I'm closing this but opening an issue on the development environment repo to track it.
