### ISSUE TITLE
Implement support for slack "buttons"

### ISSUE THREAD

**Issue by cdrage** [litaio/lita#192]
May be a bit too early for this, but it'd be awesome to add support for this somehow within Lita:
https://slackhq.com/get-more-done-with-message-buttons-5fa5b283a59#.ibdwnl23o

**Comment by jimmycuadra** [comment]
Definitely a cool feature, but features that are specific to particular chat services are not going to be supported by Lita core in the future. If you're developing Slack-specific plugins that want to take advantage of this, using a Slack API client library is the way to go.

**Comment by cdrage** [comment]
@jimmycuadra thanks man :) i'll go ahead and have a look at that then (either the lita slack plugin, or of course looking at the slack api when they decide to implement it in the future)
