### ISSUE TITLE
A way to provide a "default" route on a handler for commands?

### ISSUE THREAD

**Issue by ekilah** [litaio/lita#197]
I am wondering if a handler can easily define a default route, such that if no other routes match a command, this default route would be triggered.

It would only really make sense to use with a command, since otherwise every message would trigger the default route on the handler. but saying "lita what's going on?" could helpfully reply with something like "I don't understand. try `lita help` for a list of things I can do" if that's not a valid command.

Does this exist? I couldn't find mention of something like it in the documentation. I'm new to Lita, so thanks for entertaining me. 

I tried two routes with the same regex, and they both run - maybe, if there was a way to say only one route should run per message, I could achieve the intended result too, but that'd be more of an unintended-feature kind of thing.

**Comment by jimmycuadra** [comment]
You might be able to use the unhandled message event to do what you want: https://docs.lita.io/plugin-authoring/events/

**Comment by ekilah** [comment]
Thanks for the reply - that would be what I would expect to work for that purpose.

In using this method for this purpose, though, it seems that the [Slack RTM connection](https://github.com/litaio/lita-slack/blob/master/lib/lita/adapters/slack/rtm_connection.rb) always re-receives the last message that was sent by Lita when restarting the Lita process after a deploy.

To clarify, here's the sequence I see:

```
> me: lita valid_command
> lita: response to valid_command
> me: other message(s), not necessarily directed at lita (this is optional)
# CTRL+C lita server, restart it with `lita start`
> lita: Sorry, I don't understand the command "response to valid_command".
```
The last line is produced by my `on(:unhandled_message)` block. Can you see if you can replicate this behavior? It seems like a bug to me... or, at least, something that the adapter should filter out since it might be slack's "fault" (or feature)?

I could probably work around it by seeing if the message was sent by the bot (sorta related to https://github.com/litaio/lita-slack/pull/95), but it seems like this shouldn't be necessary? I can also make this not happen as often by filtering by `command?` in the `unhandled_message` block, but that doesn't prevent DMs from suffering from this if that's where lita's last message went.

(sorry that this potential bug report is a comment on the issue here, let me know if you'd rather I split it out onto a new one)

**Comment by ekilah** [comment]
a little more data: 

```
[2016-07-29 08:37:55 UTC] DEBUG: Dispatching message to Lita from <my UID>. # this is my unhandled message, lita replies to it immediately as expected
^C[2016-07-29 08:38:03 UTC] INFO: Disconnected from Slack.
[2016-07-29 08:38:03 UTC] DEBUG: Closing connection to the Slack Real Time Messaging API.
[2016-07-29 08:38:03 UTC] DEBUG: Closing connection to the Slack Real Time Messaging API.
bash-3.2$ lita start
[2016-07-29 08:38:04 UTC] DEBUG: Connecting to the Slack Real Time Messaging API.
[2016-07-29 08:38:05 UTC] DEBUG: Connected to the Slack Real Time Messaging API.
[2016-07-29 08:38:05 UTC] INFO: Connected to Slack.
[2016-07-29 08:38:05 UTC] DEBUG: reconnect_url event received from Slack and will be ignored.
[2016-07-29 08:38:05 UTC] DEBUG: Dispatching message to Lita from <Lita's UID> # this logs that Lita re-receives the message that it sent to me in response to the unhandled message
```

**Comment by jimmycuadra** [comment]
Without taking some time to investigate it now, this sounds like an issue only related to the Slack adapter, so I'm going to close the issue here. Please file a new issue on lita-slack if you're not able to find a satisfactory workaround!

**Comment by ekilah** [comment]
great, I'll post a new issue there. thanks!
