### ISSUE TITLE
Reply with "Command unknown" if there is no command

### ISSUE THREAD

**Issue by jaybrueder** [litaio/lita#199]
It would be great if Lita could reply with "Command unknown" or "I don't know this command" if the user asks something that Lita does not understand.

I sometimes have users using the wrong command or having typos in their messages.
Lita stays silent and then they think that Lita is down or broken.

I think it would improve the user experience.

**Comment by jimmycuadra** [comment]
You can do this with the "unhandled message" event. See #55.
