### ISSUE TITLE
Multiple handlers under namespace block configuration

### ISSUE THREAD

**Issue by tduffield** [litaio/lita#210]
Hey, so I have a sufficiently complex plugin that has multiple sub-components. The reason these components are all in one plugin is because they have a large amount of shared dependencies, and keeping them together just makes everything easier to maintain. The problem is that it appears the default configuration builder doesn't really handle namespacing as the documentation seems to indicate. I have a test that exposes the issue but before I went to far in trying to address it I wanted to make sure that this is something that you'd want to support. 

```ruby
context "with multiple handlers with the same namespace" do
  it "has all the attributes for each handler" do
    registry.register_handler(:foo) { config :bar, default: :baz }

    registry.register_handler(:moo) do
      namespace "foo"
      config :mar, default: :maz
    end

    registry.register_handler(:too) do
      namespace "foo"
      config :tar, default: :taz
    end

    expect(config.handlers.foo.bar).to eq(:baz)
    expect(config.handlers.foo.mar).to eq(:maz)
    expect(config.handlers.foo.tar).to eq(:taz)
  end
end
```

the result of this test is this: 

```
  1) Lita::DefaultConfiguration handlers config with multiple handlers with the same namespace has all the attributes for each handler
     Failure/Error: expect(config.handlers.foo.bar).to eq(:baz)

     NoMethodError:
       undefined method `bar' for #<Lita::Configuration:0x007ff5a98ae1b0>
       Did you mean?  tar
     # ./spec/lita/default_configuration_spec.rb:68:in `block (4 levels) in <top (required)>'
```

Is this the intended behavior? Is this something that Lita even supports?

**Comment by tduffield** [comment]
I should add I'm totally willing to open a PR to address this, I just wanted to make sure this is something you'd want to support before I put the time into implementation.

**Comment by jimmycuadra** [comment]
I'll need to check, as I haven't looked at the code in a while, but I believe this or something like it should already work.

**Comment by jimmycuadra** [comment]
Try defining all the config attributes in the same class. They should be shareable across any handler with the namespace as the one the attributes are defined in.

**Comment by tduffield** [comment]
I did do that, and that works. If that's the way that it needs to work, then the documentation may need to be clarified because it doesn't indicate that if you use namespaces you need to have all the config in a single class. In fact, if there is even a single config value inside a namespaced class, then load-order plays the final factor in determining which config values are present
