### ISSUE TITLE
Handle the interactive message callback

### ISSUE THREAD

**Issue by ngocmanh1609** [litaio/lita#214]
Hi guys,
I'm curently using the slack app bot to post the interactive message with button into slack, and return the command to call lita working the rest (ex: save data). I try to get this script working only on 1 bot (lita of course) but I cannot find anyway to get lita to handle the callback message from itself after pressing on Save button.
Please advice me some guides for this, thanks

**Comment by jimmycuadra** [comment]
This would be an issue for [lita-slack](https://github.com/litaio/lita-slack), but neither Lita or the Slack adapter are being actively developed.
