### ISSUE TITLE
Adding HTTP URL for adapters

### ISSUE THREAD

**Issue by grokify** [litaio/lita#216]
Is it possible to add an HTTP URL for an adapter? I know this can be added for handlers, but when I tro to add it for an adapter, I receive the following error:

```
Gem Load Error is: undefined local variable or method `http' for Lita::Adapters::Glip:Class
```

**Comment by jimmycuadra** [comment]
Can you clarify what you mean by HTTP URL? Are you trying to make an outgoing HTTP request, or add a route for incoming HTTP requests?

**Comment by grokify** [comment]
I'm trying to have the bot handle OAuth 2.0 authorization code grant for an adapter. For OAuth, I need to have a redirect URL on the bot which returns an authorization code in the URL which I will then need to extract and exchange for an access token.

Today, in a Handler, I can have  URL like the following from `lita-line`:

`http.post "/callback", :callback`

https://github.com/aar0nTw/lita-line/blob/master/lib/lita/handlers/webhook.rbhttps://github.com/aar0nTw/lita-line/blob/master/lib/lita/handlers/webhook.rb#L49

However, I cannot add a callback to an Adapter.

**Comment by jimmycuadra** [comment]
You need to use a handler for incoming HTTP requests. You can include a handler in the same gem as your adapter so users don't need to install two gems for the full functionality.
