### ISSUE TITLE
passthrough has been deprecated log spam

### ISSUE THREAD

**Issue by gonzoinc** [litaio/lita#217]
Being log spammed with the following:

> Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/lita/builds/1.1.2/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handlers/info.rb:43:in `redis_info')

Anything that can be done to stop the logspam as it looks to be causing the bot to crash after a couple days. These are being written every time a new message comes through.

**Comment by jimmycuadra** [comment]
Please try out the recently released v4.8.0.beta1 and let me know if you have any problems with it! https://github.com/litaio/lita/releases/tag/v4.8.0.beta1
