### ISSUE TITLE
my redis requires user and password, how to set in config?

### ISSUE THREAD

**Issue by blysik** [litaio/lita#219]
Hi,

The redis I have available requires setting a username in password.  How do I configure lita appropriately for this?  Thanks!

**Comment by dpritchett** [comment]
You ought to be able to fabricate a redis connection URL that includes user name, password, host, and port like so:

```rb
redis_url = "redis://username:password@redishost:portnumber"


Lita.configure do |config|
  config.redis[:url] = redis_url
end
```

**Comment by jimmycuadra** [comment]
`Lita.config.redis` is a hash that gets passed directly to `::Redis::new`, so you can use the `:user` and `:password` keys as you would with the redis-rb client: https://github.com/redis/redis-rb
