### ISSUE TITLE
http.post handler not routing - 404 not found

### ISSUE THREAD

**Issue by victorsosa** [litaio/lita#220]
Hi,

This spec is working fine as expected; but when I go to run the code for a real call then it doesn't work; it's like is not loading the handler in the app. 

Calls:
get localhost:8080/lita/info -> got response
post localhost:8080/lita/whatsapp -> 404 not found

```
require "spec_helper"

describe Lita::Handlers::WhatsAppHandler, lita_handler: true do
  it { is_expected.to route_http(:post, "/whatsapp") }

    describe "#whatsapp_messages" do
        it "writes 'OK' as a reply" do
            response = http.post("/whatsapp")
            expect(response.body).to eq("Hello, Faraday v0.17.1!")
        end
    end
end
```

What could I be missing that the handler doesn't load?

class handler
```
module Lita
  module Handlers

    class WhatsAppHandler < Handler
        http.post("/whatsapp", :process_whatsapp_messages)

        def process_whatsapp_messages(request, response)
            Lita.logger.info("whatsapp message: #{request.user_agent}")
            response.body << "Hello, #{request.user_agent}!"
        end
        Lita.register_handler(self)
    end

    class EchoHandler < Handler
      route(/^echo\s+(.+)/, :echo, command: true, help: {
              "echo TEXT" => "Replies back with TEXT."
      })

      def echo(response)
        response.reply(response.matches)
      end     
    end

        
    #Lita.register_handler(WhatsAppHandler)
    Lita.register_handler(EchoHandler)    
  end
end
```

**Comment by victorsosa** [comment]
Base on the documentation of http_router; it should be used add method to create a map to the route: https://github.com/joshbuddy/http_router#addname-options
(or the method #url instead which take a route as argument)

instead the code is using add_route method, but as the doc said:
**Routes will not be recognized unless #to has been called on it.**
the #to method is like the callback

```
  r = HttpRouter.new
  r.add('/test/:variable(.:format)').name(:my_test_path).to {|env| [200, {}, "Hey dude #{env['router.params'][:variable]}"]}
```

Line with potential issue:
https://github.com/litaio/lita/blob/c1a1f85f791b74e40ee6a1e2d53f19b5f7cbe0ba/lib/lita/rack_app.rb#L74

I recomend the use of the #url method to avoid a big refactor and fix the issue.

**Comment by victorsosa** [comment]
@jimmycuadra any idea about this issue?

**Comment by jimmycuadra** [comment]
Your code works as expected to me. Can you provide more info about how you're testing it with a real HTTP request outside of the test suite?

The "route.to" call that you thought might be missing can be found here: https://github.com/litaio/lita/blob/964a827c0b99f742ddbcd143b178e79c59aed56a/lib/lita/http_route.rb#L68

**Comment by victorsosa** [comment]
@jimmycuadra Thanks for you answer, 

> Lita does not automatically mount your HTTP routes at the path /lita. That's just where the routes that are provided with Lita itself are defined. You should get the response you expect if you POST to /whatsapp rather than /lita/whatsapp.

**Yes that's the problem**

to test just use any test client in you browser like this one:
https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

prepare 2 calls:
get localhost:8080/lita/info -> you should get a response
post localhost:8080/lita/whatsapp -> you should get 404 not found

**Comment by victorsosa** [comment]
Still getting the 404 when I try:
post localhost:8080/whatsapp

**Comment by jimmycuadra** [comment]
It works for me:

```
$ curl -X POST http://localhost:8080/whatsapp
Hello, curl/7.64.1!
```

The issue might be with the program you're using to test, as Lita is behaving as expected when using the code from top of the issue.

**Comment by victorsosa** [comment]
It seems a problem in the project; because now I was able to run it but in another new project, thanks
