### ISSUE TITLE
Lita should be able to connect to multiple chat services at the same time

### ISSUE THREAD

**Issue by zacstewart** [litaio/lita#37]
I'd like to be able to run the same robot on both IRC and Campfire (and ideally any number of other services). The robot should share persistence across both services.

For example, using lita-karma:

> Campfire-me> something~~
> Campfire-Lita> something: 0
> IRC-me> something++
> Campfire-me> something~~
> Campfire-Lita> something: 1

**Comment by Serhiy-Nazarov** [comment]
@jimmycuadra 
I want to implement bot that communicate few users between each other. But each user can use different adapter. For example one user uses Telegram, next one slack, but at the same moment they should have the same context (karma extantion, as example). How I can do it by the best way?
