### ISSUE TITLE
Consider transferring repository to litaio organization

### ISSUE THREAD

**Issue by technicalpickles** [litaio/lita#71]
Looks like new things are going over to the [litaio organization](https://github.com/litaio), so it might be worth transferring this repository over there.

Redirects, both in terms of viewing in a browser or using a git client, are handled automatically after transferring (see https://help.github.com/articles/transferring-a-repository/ and search for redirect).

**Comment by jimmycuadra** [comment]
I'm going to leave it under my account for the time being but I will keep thinking about this as more projects around Lita develop. Thanks again for bringing it up!

**Comment by jimmycuadra** [comment]
Reopening because I am planning to do this in the near future.

**Comment by jimmycuadra** [comment]
Done! Thanks.
