### ISSUE TITLE
Add an easy way to find a user's primary ID

### ISSUE THREAD

**Issue by jimmycuadra** [litaio/lita#72]
Because some functionality (notably `config.robot.admins`) require a user's primary ID, which is unique, there should be an easy way of finding out what a given user's ID is. This is often not easy to get, such as on IRC and Slack. Perhaps a built-in handler that worked something like this:

```
You: Lita, users find carl
Lita: Carl the Pug, ID: U0123456789
```

**Comment by Gaurav2Github** [comment]
I am also trying to load the admins for my bot which is using hipchat adapter.
Adding user id in my lita config, provided by following 'users find' command 
```
## in hipchat
Lita users find <username>
<username> (ID: <userid>, Mention name: <mentionname>)

## in lita_config.rb
config.robot.admins = ["userid"]
````
After loading this config. It does not load any auth users
```
## in hipchat
Lita auth list
There are no authorization groups yet
```
Any suggestions, what can be done to load admins or admin groups?

**Comment by jimmycuadra** [comment]
Admins are a special group not displayed by the `auth list` command. It should be working correctly with that configuration.

**Comment by Gaurav2Github** [comment]
Thanks for the clarity.
I am trying to load new authorization groups.
Any advise on that?

**Comment by jimmycuadra** [comment]
http://docs.lita.io/getting-started/usage/#authorization-groups should have everything you need. The groups get automatically created when you add a user to one.

**Comment by Gaurav2Github** [comment]
Worked for me now. 
The userIds in config.robot.admins list had some extra characters. :D
Thanks for responding.
