### ISSUE TITLE
Allow me to cull some help messages.

### ISSUE THREAD

**Issue by MrJoy** [litaio/lita#98]
I want to add some plugins to Lita, but not clutter the help with everything they can do.  Notably, the `lita-memegen` plugin adds a lot of noise.

Some way of curating the help display would be immensely helpful.

**Comment by jimmycuadra** [comment]
Agreed. The lack of structure of the help command's output has been brought up as a problem in general. I'm interested to hear any ideas anyone has about how it could be presented/filtered in a way that's more approachable.

**Comment by MrJoy** [comment]
Well, there's kinda two basic ideas that come to mind.

One is grouping of messages and adding sub-help screens.  So you do `lita help` and get a list of handlers, with descriptions of each.  You do `lita help <handler>` and you get the help for that module.

That one's pretty straightforward and you can shore up the lack of extant descriptions for modules by falling back to the Gem description field if a description isn't provided.  It'll go a reasonable way to compartmentalizing the chaos in most cases.

It may not do as well if the logical division of functionality in my handlers doesn't match the physical division very well.  I may be facing that situation very soon, although I'm not 100% convinced I'm not Doing it Wrong<tm> right now so it may be a red herring to focus too much on that eventuality.

An option that's simultaneously simpler and more complex would be to be able to use config options to quash specific help messages, but there's no graceful way of addressing specific routes right now other than perhaps via an example message.  The ability to name routes would help but would add to the complexity of routes and wouldn't help with existing modules that aren't always kept terribly up-to-date.

A third option would be to allow explicit groupings.  Whether that would work in a hierarchical fashion (handler defines a set of groupings, but those can be overridden via `lita_config.rb`, etc), have a totally or different separation of concerns (explicit config only, you're on your own to handle third party handlers) makes it a thorny issue and it also faces the how-do-I-reliably-and-specifically-reference-a-route issue.

If I had to pick an easy win, I'd say go with group-by-handler for now, and see if that scratches the itch well enough for folks.

**Comment by jimmycuadra** [comment]
Sounds reasonable.

**Comment by brodock** [comment]
How it is today:
```
> lita: help
lita: help - Lists help information for terms and command the robot will respond to.
lita: help COMMAND - Lists help information for terms or commands that begin with COMMAND.
lita: info - Replies with the current version of Lita.
lita: karma worst [N] - Lists the bottom N terms by karma. N defaults to 5.
lita: karma best [N] - Lists the top N terms by karma. N defaults to 5.
lita: karma modified TERM - Lists the names of users who have upvoted or downvoted TERM.
TERM++ - Increments TERM by one.
TERM-- - Decrements TERM by one.
TERM~~ - Shows the current karma of TERM.
```

I see clutter with the mention name in everyline, (which also differs from adapter to adapter), it's also mixed with commands and "random keywords"

Exploring a minimal help message alternative:

```
> lita: help
Commands you can ask me directly:
* help - Display this help information
* help all terms - Lists help information for all terms the robot will respond to.
* help all commands - Lists help information for all commands the robot will respond to.
* help all - Lists help information for terms and command the robot will respond to.

> lita: help all terms
Terms I'm programmed to react when someone says:
* TERM++ - Increments TERM by one.
* TERM-- - Decrements TERM by one.
* TERM~~ - Shows the current karma of TERM.

> lita: help all commands
Commands you can ask me directly:
* help - Display this help information
* help all terms - Lists help information for all terms the robot will respond to.
* help all commands - Lists help information for all commands the robot will respond to.
* help all - Lists help information for terms and command the robot will respond to.
* info - Replies with the current version of Lita.
* karma worst [N] - Lists the bottom N terms by karma. N defaults to 5.
* karma best [N] - Lists the top N terms by karma. N defaults to 5.
* karma modified TERM - Lists the names of users who have upvoted or downvoted TERM.

> lita: help all
Commands you can ask me directly:
* help - Display this help information
* help all terms - Lists help information for all terms the robot will respond to.
* help all commands - Lists help information for all commands the robot will respond to.
* help all - Lists help information for terms and command the robot will respond to.
* info - Replies with the current version of Lita.
* karma worst [N] - Lists the bottom N terms by karma. N defaults to 5.
* karma best [N] - Lists the top N terms by karma. N defaults to 5.
* karma modified TERM - Lists the names of users who have upvoted or downvoted TERM.

Terms I'm programmed to react when someone says:
* TERM++ - Increments TERM by one.
* TERM-- - Decrements TERM by one.
* TERM~~ - Shows the current karma of TERM.
```

**Comment by jimmycuadra** [comment]
I like that way of differentiating between "overheard" message and command much better. I will definitely do it this way when I make these updates.

**Comment by tristaneuan** [comment]
I have a pull request open with some proposed changes; feedback from anyone following this issue would be appreciated: https://github.com/litaio/lita-default-handlers/pull/1

**Comment by MrJoy** [comment]
Cursory look at it looks good!

**Comment by jimmycuadra** [comment]
Tristan's PR on lita-default-handlers is merged, so this is now addressed. It'll be in Lita 5!
